<script setup lang="ts">
import { label, person, time } from '../../lib/presentation';
import type { HandoverSnapshot } from './types';
defineProps<{ snapshot: HandoverSnapshot; prefix: string }>();
function factKind(kind: string) { return ({ HUMAN_STATEMENT: '사람 진술', RECORD: '기록', SYSTEM_STATE: '시스템 상태' } as Record<string, string>)[kind] ?? kind; }
function content(value: unknown) { return typeof value === 'string' ? value : JSON.stringify(value, null, 2); }
</script>
<template>
  <div class="handover-snapshot">
    <p v-if="snapshot.review_required" class="notice error"><strong>후속 검토 필요</strong> · {{ snapshot.review_reason }}<br>인수해도 반려 사유와 검토 필요 상태는 유지됩니다.</p>
    <dl><dt>이 내용의 사건 상태 / 버전</dt><dd>{{ label(snapshot.status) }} / {{ snapshot.version }}</dd><dt>당시 사건 책임자</dt><dd>{{ snapshot.owner?.display_name ?? person(snapshot.owner_id) }}</dd><dt>당시 작업 담당자</dt><dd>{{ snapshot.assignee?.display_name ?? person(snapshot.assignee_id) }}</dd></dl>
    <section :aria-labelledby="`${prefix}-messages`"><h3 :id="`${prefix}-messages`">보존된 원문·답변·작업 결과</h3><p v-if="!snapshot.messages?.length">저장된 원문이 없습니다.</p><ol class="timeline"><li v-for="message in snapshot.messages" :key="message.id"><div class="record-meta"><strong>{{ message.kind }}</strong><span>{{ time(message.received_at) }}</span></div><p class="preserve-lines">{{ message.text }}</p><small>작성자 {{ person(message.author_id) }} · Message {{ message.id }}</small><p v-if="message.reply_to_request_id">답변 질문 {{ message.reply_to_request_id }}</p><p v-if="message.correction_of">정정 대상 {{ message.correction_of }} · 이전 원문 보존</p></li></ol></section>
    <section :aria-labelledby="`${prefix}-requests`"><h3 :id="`${prefix}-requests`">질문과 지정 답변자</h3><p v-if="!snapshot.requests?.length">저장된 질문이 없습니다.</p><article v-for="request in snapshot.requests" :key="request.id" class="question-card"><span class="badge" :class="{ amber: request.status === 'OPEN' }">{{ request.is_required ? '필수 질문' : '선택 질문' }} · {{ request.status === 'OPEN' ? '답변 대기' : '답변 완료' }}</span><h4>{{ request.question }}</h4><p>{{ request.purpose_code }} · 답변 대상 {{ person(request.target_user_id) }}</p><p class="identifier">Request {{ request.id }}</p><p>근거 {{ request.evidence_refs?.join(', ') || '없음' }}</p><blockquote v-if="request.response_message_id">{{ snapshot.messages?.find(message => message.id === request.response_message_id)?.text ?? '원문 이력에서 답변을 확인하세요.' }}</blockquote><p v-if="request.response_message_id" class="identifier">답변 Message {{ request.response_message_id }}</p></article><p v-if="snapshot.requests?.some(request => request.status === 'OPEN')" class="muted">인수 후에도 지정 답변자와 필수 질문 대기는 유지됩니다.</p></section>
    <section :aria-labelledby="`${prefix}-actions`"><h3 :id="`${prefix}-actions`">작업·승인·결과</h3><p v-if="!snapshot.actions?.length">등록된 작업이 없습니다.</p><article v-for="action in snapshot.actions" :key="action.id" class="question-card"><h4>{{ action.title ?? '후속 작업' }}</h4><p><span class="badge">{{ ({ PROPOSED: '승인 대기', APPROVED: '승인됨', IN_PROGRESS: '수행 중', COMPLETED: '결과 제출 완료', REJECTED: '승인 반려' } as Record<string,string>)[action.status] ?? action.status }}</span> · Action {{ action.id }}</p><p class="preserve-lines">{{ action.scope }}</p><p>작업 담당자 {{ person(action.assignee_id) }} · 기한 {{ time(action.due_at) }}</p><p v-if="action.completion_criteria" class="preserve-lines">완료 기준: {{ content(action.completion_criteria) }}</p><blockquote v-if="action.result_message_id">{{ snapshot.messages?.find(message => message.id === action.result_message_id)?.text ?? '저장된 결과 원문을 확인하세요.' }}</blockquote><p v-if="action.completion_evidence_id">결과 근거 {{ action.completion_evidence_id }}</p><p>참조 근거 {{ action.evidence_refs?.join(', ') || '없음' }}</p><div v-for="approval in snapshot.approvals?.filter(value => value.action_id === action.id)" :key="approval.id"><h5>{{ approval.decision === 'APPROVE' ? '사람 승인' : '사람 반려' }}</h5><p>{{ approval.reason }}</p><p>{{ person(approval.actor_id) }} · {{ time(approval.created_at) }} · 승인 대상 revision {{ approval.action_revision }}</p><details><summary>당시 승인 내용</summary><pre>{{ content(approval.approved_payload_snapshot) }}</pre><p class="identifier">승인 {{ approval.id }} · 내용 확인값 {{ approval.payload_hash }}</p></details></div></article></section>
    <section :aria-labelledby="`${prefix}-facts`"><h3 :id="`${prefix}-facts`">근거가 연결된 기록과 분석</h3><ul class="facts"><li v-for="(fact, index) in snapshot.facts ?? []" :key="index"><span class="category">{{ factKind(fact.kind) }}</span><p>{{ fact.text }}</p><small>근거 {{ fact.source_refs.join(', ') }}</small></li></ul><template v-if="snapshot.analysis"><p :class="snapshot.analysis.is_stale ? 'notice amber' : 'muted'">{{ snapshot.analysis.is_stale ? '이전 정보에 대한 분석 · 현재 확인 사실이 아닙니다.' : '이 snapshot의 AI 분석 참고' }} 분석 기준 {{ snapshot.analysis.base_version }} / snapshot 사건 버전 {{ snapshot.version }}</p><p>{{ snapshot.analysis.reason }}</p><details><summary>분석 당시의 기록·가설·미확인 정보</summary><ul><li v-for="(fact, index) in snapshot.analysis.facts ?? []" :key="index">{{ factKind(fact.kind) }}: {{ fact.text }} · 근거 {{ fact.source_refs.join(', ') }}</li></ul><h4>가설 · 확인된 사실 아님</h4><ul><li v-for="(hypothesis, index) in snapshot.analysis.hypotheses ?? []" :key="index">{{ hypothesis }}</li></ul><h4>미확인 정보</h4><ul><li v-for="(missing, index) in snapshot.analysis.missing_information ?? []" :key="index">{{ missing }}</li></ul></details></template><p v-else>AI 분석이 없어도 원문과 저장된 업무 내용을 인수할 수 있습니다.</p></section>
    <section :aria-labelledby="`${prefix}-evidence`"><h3 :id="`${prefix}-evidence`">당시 근거와 출처</h3><p v-if="!snapshot.evidence?.length">저장된 근거가 없습니다.</p><details v-for="evidence in snapshot.evidence" :key="evidence.id"><summary>{{ evidence.source_type }} · {{ evidence.source_id }} · 버전 {{ evidence.source_version }}</summary><blockquote class="preserve-lines">{{ evidence.excerpt }}</blockquote><p>위치 {{ evidence.source_location ?? '미수집' }} · 관측 {{ time(evidence.observed_at) }} · 조회 {{ time(evidence.captured_at) }}</p><p>적용 범위 {{ content(evidence.applicability) }}</p><p class="identifier">Evidence {{ evidence.id }}</p></details></section>
  </div>
</template>
<style scoped>
.handover-snapshot section { margin-top: 1.5rem; }
.handover-snapshot pre { white-space: pre-wrap; overflow-wrap: anywhere; }
.handover-snapshot details { margin: .7rem 0; }
</style>
