"""Frozen PostgreSQL schema for F1 and shared read projections.

This revision is independent of application model imports. Subsequent changes
require a new revision so rebuilding the original schema remains deterministic.
"""
from alembic import op

revision = "0001_f1_foundation"
down_revision = None
branch_labels = None
depends_on = None

UPGRADE_SQL = (
    "CREATE TABLE users (\n\tsite_id VARCHAR(36) NOT NULL, \n\taccount_key VARCHAR(80) NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\trole VARCHAR(20) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCHECK (role IN ('worker','supervisor')), \n\tUNIQUE (account_key)\n)",
    'CREATE INDEX ix_users_site_id ON users (site_id)',
    'CREATE TABLE documents (\n\tsite_id VARCHAR(36) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tversion VARCHAR(50) NOT NULL, \n\tapproval_status VARCHAR(30) NOT NULL, \n\tequipment_ids JSON NOT NULL, \n\tsource_location TEXT NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_documents_site_id ON documents (site_id)',
    'CREATE TABLE shifts (\n\tsite_id VARCHAR(36) NOT NULL, \n\tlabel VARCHAR(100) NOT NULL, \n\tstarts_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tends_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsupervisor_id VARCHAR(36) NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(supervisor_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_shifts_site_id ON shifts (site_id)',
    'CREATE UNIQUE INDEX uq_active_shift_site ON shifts (site_id) WHERE active = true',
    'CREATE TABLE session_tokens (\n\tuser_id VARCHAR(36) NOT NULL, \n\ttoken_hash VARCHAR(64) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tUNIQUE (token_hash)\n)',
    'CREATE TABLE equipment (\n\tsite_id VARCHAR(36) NOT NULL, \n\tcode VARCHAR(80) NOT NULL, \n\tlabel VARCHAR(200) NOT NULL, \n\taliases JSON NOT NULL, \n\tdefault_maintainer_id VARCHAR(36) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (site_id, code), \n\tFOREIGN KEY(default_maintainer_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_equipment_site_id ON equipment (site_id)',
    'CREATE TABLE document_chunks (\n\tdocument_id VARCHAR(36) NOT NULL, \n\tposition INTEGER NOT NULL, \n\ttext TEXT NOT NULL, \n\tsource_location TEXT NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (document_id, position), \n\tFOREIGN KEY(document_id) REFERENCES documents (id)\n)',
    'CREATE INDEX ix_document_chunks_document_id ON document_chunks (document_id)',
    'CREATE TABLE command_receipts (\n\tsite_id VARCHAR(36) NOT NULL, \n\tactor_id VARCHAR(36) NOT NULL, \n\tidempotency_key VARCHAR(200) NOT NULL, \n\tpayload_hash VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\thttp_status INTEGER NOT NULL, \n\tresponse_json JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (site_id, actor_id, idempotency_key), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    'CREATE TABLE shift_assignments (\n\tshift_occurrence_id VARCHAR(36) NOT NULL, \n\tuser_id VARCHAR(36) NOT NULL, \n\tduty VARCHAR(30) NOT NULL, \n\tPRIMARY KEY (shift_occurrence_id, user_id), \n\tFOREIGN KEY(shift_occurrence_id) REFERENCES shifts (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)',
    "CREATE TABLE incidents (\n\tdisplay_id VARCHAR(60) NOT NULL, \n\ttitle VARCHAR(120) NOT NULL, \n\tsite_id VARCHAR(36) NOT NULL, \n\tequipment_id VARCHAR(36) NOT NULL, \n\treporter_id VARCHAR(36) NOT NULL, \n\torigin_shift_occurrence_id VARCHAR(36) NOT NULL, \n\towner_shift_occurrence_id VARCHAR(36) NOT NULL, \n\towner_id VARCHAR(36) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tversion INTEGER NOT NULL, \n\taction_generation INTEGER NOT NULL, \n\treview_required BOOLEAN NOT NULL, \n\treview_reason TEXT, \n\tanalysis JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tresolved_at TIMESTAMP WITH TIME ZONE, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCHECK (version >= 1), \n\tCHECK (action_generation = 1), \n\tCHECK (status IN ('OPEN','INVESTIGATING','ACTION_REQUIRED','IN_PROGRESS','PENDING_VERIFICATION','RESOLVED')), \n\tUNIQUE (display_id), \n\tFOREIGN KEY(equipment_id) REFERENCES equipment (id), \n\tFOREIGN KEY(reporter_id) REFERENCES users (id), \n\tFOREIGN KEY(origin_shift_occurrence_id) REFERENCES shifts (id), \n\tFOREIGN KEY(owner_shift_occurrence_id) REFERENCES shifts (id), \n\tFOREIGN KEY(owner_id) REFERENCES users (id)\n)",
    'CREATE INDEX ix_incidents_site_id ON incidents (site_id)',
    'CREATE TABLE equipment_logs (\n\tsite_id VARCHAR(36) NOT NULL, \n\tequipment_id VARCHAR(36) NOT NULL, \n\tauthor_id VARCHAR(36) NOT NULL, \n\ttext TEXT NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_location TEXT NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(equipment_id) REFERENCES equipment (id), \n\tFOREIGN KEY(author_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_equipment_logs_site_id ON equipment_logs (site_id)',
    'CREATE TABLE handovers (\n\tsite_id VARCHAR(36) NOT NULL, \n\tfrom_shift_occurrence_id VARCHAR(36) NOT NULL, \n\tto_shift_occurrence_id VARCHAR(36) NOT NULL, \n\treceiver_id VARCHAR(36) NOT NULL, \n\tcutoff_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_by VARCHAR(36) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (site_id, from_shift_occurrence_id, to_shift_occurrence_id), \n\tFOREIGN KEY(from_shift_occurrence_id) REFERENCES shifts (id), \n\tFOREIGN KEY(to_shift_occurrence_id) REFERENCES shifts (id), \n\tFOREIGN KEY(receiver_id) REFERENCES users (id), \n\tFOREIGN KEY(created_by) REFERENCES users (id)\n)',
    "CREATE TABLE messages (\n\tsite_id VARCHAR(36) NOT NULL, \n\tincident_id VARCHAR(36) NOT NULL, \n\tauthor_id VARCHAR(36) NOT NULL, \n\tkind VARCHAR(30) NOT NULL, \n\ttext TEXT NOT NULL, \n\treply_to_request_id VARCHAR(36), \n\taction_id VARCHAR(36), \n\tcorrection_of VARCHAR(36), \n\tobserved_at TIMESTAMP WITH TIME ZONE, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCHECK (kind IN ('REPORT','NOTE','REPLY','ACTION_RESULT','CORRECTION')), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(author_id) REFERENCES users (id), \n\tFOREIGN KEY(correction_of) REFERENCES messages (id)\n)",
    'CREATE INDEX ix_messages_incident_id ON messages (incident_id)',
    'CREATE INDEX ix_messages_site_id ON messages (site_id)',
    "CREATE TABLE requests (\n\tincident_id VARCHAR(36) NOT NULL, \n\ttarget_user_id VARCHAR(36) NOT NULL, \n\tpurpose_code VARCHAR(30) NOT NULL, \n\tquestion TEXT NOT NULL, \n\tis_required BOOLEAN NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tevidence_refs JSON NOT NULL, \n\tresponse_message_id VARCHAR(36), \n\tversion INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tanswered_at TIMESTAMP WITH TIME ZONE, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCHECK (purpose_code IN ('VERIFY_SCOPE','VERIFY_RESULT')), \n\tCHECK (status IN ('OPEN','ANSWERED')), \n\tCHECK (is_required = true), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(target_user_id) REFERENCES users (id)\n)",
    "CREATE UNIQUE INDEX uq_open_request_purpose ON requests (incident_id, target_user_id, purpose_code) WHERE status = 'OPEN'",
    'CREATE INDEX ix_requests_incident_id ON requests (incident_id)',
    'CREATE TABLE evidence (\n\tsite_id VARCHAR(36) NOT NULL, \n\tincident_id VARCHAR(36) NOT NULL, \n\tsource_type VARCHAR(30) NOT NULL, \n\tsource_id VARCHAR(100) NOT NULL, \n\tsource_version VARCHAR(50) NOT NULL, \n\tequipment_id VARCHAR(36), \n\tapplicability JSON NOT NULL, \n\tdocument_approval VARCHAR(30), \n\texcerpt TEXT NOT NULL, \n\tcontent_hash VARCHAR(64) NOT NULL, \n\tsource_location TEXT NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE, \n\tcaptured_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(equipment_id) REFERENCES equipment (id)\n)',
    'CREATE INDEX ix_evidence_incident_id ON evidence (incident_id)',
    'CREATE INDEX ix_evidence_site_id ON evidence (site_id)',
    'CREATE TABLE actions (\n\tincident_id VARCHAR(36) NOT NULL, \n\taction_slot VARCHAR(30) NOT NULL, \n\taction_generation INTEGER NOT NULL, \n\ttrigger_event_id VARCHAR(36), \n\ttitle VARCHAR(200) NOT NULL, \n\tscope TEXT NOT NULL, \n\tcompletion_criteria JSON NOT NULL, \n\tassignee_id VARCHAR(36) NOT NULL, \n\tdue_at TIMESTAMP WITH TIME ZONE, \n\tis_required BOOLEAN NOT NULL, \n\tevidence_refs JSON NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\trevision INTEGER NOT NULL, \n\tversion INTEGER NOT NULL, \n\tproposed_by_run_id VARCHAR(36), \n\tresult_message_id VARCHAR(36), \n\tcompletion_evidence_id VARCHAR(36), \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (incident_id, action_slot, action_generation), \n\tCHECK (action_generation = 1), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(assignee_id) REFERENCES users (id)\n)',
    "CREATE UNIQUE INDEX uq_active_main_action ON actions (incident_id, action_slot) WHERE status IN ('PROPOSED','APPROVED','IN_PROGRESS')",
    'CREATE INDEX ix_actions_incident_id ON actions (incident_id)',
    'CREATE TABLE verifications (\n\tincident_id VARCHAR(36) NOT NULL, \n\tdecision VARCHAR(20) NOT NULL, \n\tnotes TEXT NOT NULL, \n\tevidence_refs JSON NOT NULL, \n\tchecked_version INTEGER NOT NULL, \n\tapplied_version INTEGER NOT NULL, \n\tactor_id VARCHAR(36) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    'CREATE TABLE resolution_cases (\n\tincident_id VARCHAR(36), \n\tsite_id VARCHAR(36) NOT NULL, \n\tequipment_id VARCHAR(36) NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tresolved_version INTEGER NOT NULL, \n\tverification_id VARCHAR(36), \n\tsnapshot_json JSON NOT NULL, \n\tevidence_refs JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (incident_id, resolved_version), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(equipment_id) REFERENCES equipment (id)\n)',
    'CREATE INDEX ix_resolution_cases_site_id ON resolution_cases (site_id)',
    'CREATE TABLE handover_items (\n\thandover_id VARCHAR(36) NOT NULL, \n\tincident_id VARCHAR(36) NOT NULL, \n\tlatest_revision INTEGER NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (handover_id, incident_id), \n\tFOREIGN KEY(handover_id) REFERENCES handovers (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n)',
    'CREATE INDEX ix_handover_items_incident_id ON handover_items (incident_id)',
    'CREATE TABLE events (\n\tsite_id VARCHAR(36) NOT NULL, \n\tincident_id VARCHAR(36) NOT NULL, \n\ttype VARCHAR(80) NOT NULL, \n\tactor_id VARCHAR(36), \n\trelated_ids JSON NOT NULL, \n\tpayload JSON NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_events_incident_id ON events (incident_id)',
    'CREATE INDEX ix_events_site_id ON events (site_id)',
    'CREATE TABLE approvals (\n\taction_id VARCHAR(36) NOT NULL, \n\taction_revision INTEGER NOT NULL, \n\tdecision VARCHAR(20) NOT NULL, \n\treason TEXT NOT NULL, \n\tpayload_hash VARCHAR(64) NOT NULL, \n\tapproved_payload_snapshot JSON NOT NULL, \n\tactor_id VARCHAR(36) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(action_id) REFERENCES actions (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_approvals_action_id ON approvals (action_id)',
    'CREATE TABLE handover_item_revisions (\n\titem_id VARCHAR(36) NOT NULL, \n\trevision INTEGER NOT NULL, \n\tsnapshot_version INTEGER NOT NULL, \n\tsnapshot_json JSON NOT NULL, \n\tsnapshot_token VARCHAR(128) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (item_id, revision), \n\tFOREIGN KEY(item_id) REFERENCES handover_items (id)\n)',
    'CREATE TABLE handover_acks (\n\titem_id VARCHAR(36) NOT NULL, \n\trevision INTEGER NOT NULL, \n\tactor_id VARCHAR(36) NOT NULL, \n\tprevious_owner_id VARCHAR(36) NOT NULL, \n\tnew_owner_id VARCHAR(36) NOT NULL, \n\tack_applied_version INTEGER NOT NULL, \n\tacknowledged_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (item_id, revision), \n\tFOREIGN KEY(item_id) REFERENCES handover_items (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id), \n\tFOREIGN KEY(previous_owner_id) REFERENCES users (id), \n\tFOREIGN KEY(new_owner_id) REFERENCES users (id)\n)',
    "CREATE TABLE jobs (\n\tincident_id VARCHAR(36) NOT NULL, \n\ttrigger_event_id VARCHAR(36) NOT NULL, \n\tjob_kind VARCHAR(30) NOT NULL, \n\tdedupe_key VARCHAR(160) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tattempt INTEGER NOT NULL, \n\tlease_token VARCHAR(80), \n\tlease_expires_at TIMESTAMP WITH TIME ZONE, \n\tavailable_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_error JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (incident_id, trigger_event_id, job_kind), \n\tCHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','SUPERSEDED')), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id), \n\tFOREIGN KEY(trigger_event_id) REFERENCES events (id), \n\tUNIQUE (dedupe_key)\n)",
    'CREATE INDEX ix_jobs_incident_id ON jobs (incident_id)',
    'CREATE TABLE agent_runs (\n\tjob_id VARCHAR(36) NOT NULL, \n\tattempt INTEGER NOT NULL, \n\ttrigger_event_id VARCHAR(36) NOT NULL, \n\tinput_version INTEGER, \n\tapplied_version INTEGER, \n\tstatus VARCHAR(20) NOT NULL, \n\tmode VARCHAR(20) NOT NULL, \n\tmodel_id VARCHAR(120), \n\tprompt_version VARCHAR(40) NOT NULL, \n\ttool_schema_version VARCHAR(40) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tdecision_json JSON, \n\tsteps_json JSON NOT NULL, \n\tusage_json JSON, \n\terror_json JSON, \n\tmetadata_json JSON NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (job_id, attempt), \n\tFOREIGN KEY(job_id) REFERENCES jobs (id)\n)',
    'CREATE INDEX ix_agent_runs_job_id ON agent_runs (job_id)',
    'CREATE TABLE action_drafts (\n\trun_id VARCHAR(36) NOT NULL, \n\tincident_id VARCHAR(36) NOT NULL, \n\tinput_version INTEGER NOT NULL, \n\tpayload_json JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(run_id) REFERENCES agent_runs (id), \n\tFOREIGN KEY(incident_id) REFERENCES incidents (id)\n)',
    'CREATE INDEX ix_action_drafts_run_id ON action_drafts (run_id)',
    'ALTER TABLE messages ADD CONSTRAINT fk_message_request FOREIGN KEY(reply_to_request_id) REFERENCES requests (id)',
    'ALTER TABLE requests ADD CONSTRAINT fk_request_response FOREIGN KEY(response_message_id) REFERENCES messages (id)',
    'ALTER TABLE messages ADD CONSTRAINT fk_message_action FOREIGN KEY(action_id) REFERENCES actions (id)',
)

TABLE_NAMES = ('users', 'shifts', 'session_tokens', 'shift_assignments', 'equipment', 'incidents', 'messages', 'requests', 'evidence', 'documents', 'document_chunks', 'equipment_logs', 'actions', 'approvals', 'verifications', 'resolution_cases', 'handovers', 'handover_items', 'handover_item_revisions', 'handover_acks', 'events', 'command_receipts', 'jobs', 'agent_runs', 'action_drafts')

def upgrade():
    for statement in UPGRADE_SQL:
        op.execute(statement)


def downgrade():
    for name in reversed(TABLE_NAMES):
        op.execute(f'DROP TABLE "{name}" CASCADE')
