"""foundation schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('account_key', sa.String(length=40), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("role IN ('worker','supervisor')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_users_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('account_key', name=op.f('uq_users_account_key'))
    )
    op.create_table('command_receipts',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'COMPLETED' OR (http_status IS NOT NULL AND response_json IS NOT NULL)", name='ck_receipts_response'),
    sa.CheckConstraint("status IN ('RUNNING','COMPLETED')", name='ck_receipts_state'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_command_receipts_actor_id_users')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_command_receipts_site_id_sites')),
    sa.PrimaryKeyConstraint('site_id', 'actor_id', 'idempotency_key', name=op.f('pk_command_receipts'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_maintainer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_maintainer_id'], ['users.id'], name=op.f('fk_equipment_default_maintainer_id_users')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_equipment_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('site_id', 'code', name=op.f('uq_equipment_site_id'))
    )
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_shifts_interval'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_shifts_site_id_sites')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('fk_shifts_supervisor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('origin_shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('owner_shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('action_generation', sa.Integer(), server_default='1', nullable=False),
    sa.Column('review_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN','INVESTIGATING','ACTION_REQUIRED','IN_PROGRESS','PENDING_VERIFICATION','RESOLVED')", name='ck_incidents_status'),
    sa.CheckConstraint('version >= 1 AND action_generation = 1', name='ck_incidents_version'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_incidents_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['origin_shift_occurrence_id'], ['shifts.id'], name=op.f('fk_incidents_origin_shift_occurrence_id_shifts')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_incidents_owner_id_users')),
    sa.ForeignKeyConstraint(['owner_shift_occurrence_id'], ['shifts.id'], name=op.f('fk_incidents_owner_shift_occurrence_id_shifts')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_incidents_reporter_id_users')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_incidents_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('display_id', name=op.f('uq_incidents_display_id'))
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_occurrence_id'], ['shifts.id'], name=op.f('fk_sessions_shift_occurrence_id_shifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_table('shift_assignments',
    sa.Column('shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('duty', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['shift_occurrence_id'], ['shifts.id'], name=op.f('fk_shift_assignments_shift_occurrence_id_shifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shift_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('shift_occurrence_id', 'user_id', 'duty', name=op.f('pk_shift_assignments'))
    )
    op.create_table('shift_pairs',
    sa.Column('from_shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('to_shift_occurrence_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('from_shift_occurrence_id != to_shift_occurrence_id', name='ck_shift_pairs_distinct'),
    sa.ForeignKeyConstraint(['from_shift_occurrence_id'], ['shifts.id'], name=op.f('fk_shift_pairs_from_shift_occurrence_id_shifts')),
    sa.ForeignKeyConstraint(['to_shift_occurrence_id'], ['shifts.id'], name=op.f('fk_shift_pairs_to_shift_occurrence_id_shifts')),
    sa.PrimaryKeyConstraint('from_shift_occurrence_id', 'to_shift_occurrence_id', name=op.f('pk_shift_pairs'))
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('related_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_events_actor_id_users')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_events_incident_id_incidents')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_events_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_approval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('message','log','sop','case','completion_report')", name='ck_evidence_source'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_evidence_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evidence_incident_id_incidents')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_evidence_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reply_to_request_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('correction_of', sa.Uuid(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('REPORT','NOTE','REPLY','ACTION_RESULT','CORRECTION')", name='ck_messages_kind'),
    sa.CheckConstraint('length(btrim(text)) > 0', name='ck_messages_text'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_messages_author_id_users')),
    sa.ForeignKeyConstraint(['correction_of'], ['messages.id'], name=op.f('fk_messages_correction_of_messages')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_messages_incident_id_incidents')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_messages_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=False),
    sa.Column('job_kind', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='QUEUED', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'RUNNING' OR (lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)", name='ck_jobs_lease'),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','SUPERSEDED')", name='ck_jobs_status'),
    sa.CheckConstraint('attempt >= 0', name='ck_jobs_attempt'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_jobs_incident_id_incidents')),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], name=op.f('fk_jobs_trigger_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_jobs_dedupe_key')),
    sa.UniqueConstraint('incident_id', 'trigger_event_id', 'job_kind', name='uq_jobs_trigger')
    )
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose_code', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_message_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose_code IN ('VERIFY_SCOPE','VERIFY_RESULT')", name='ck_requests_purpose'),
    sa.CheckConstraint("status IN ('OPEN','ANSWERED') AND version >= 1", name='ck_requests_state'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_requests_incident_id_incidents')),
    sa.ForeignKeyConstraint(['response_message_id'], ['messages.id'], name=op.f('fk_requests_response_message_id_messages')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_requests_target_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_index('uq_requests_open', 'requests', ['incident_id', 'target_user_id', 'purpose_code'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('tool_schema_version', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING','WAITING_INPUT','SUCCEEDED','FAILED','SUPERSEDED')", name='ck_runs_status'),
    sa.CheckConstraint('attempt >= 1 AND input_version >= 1', name='ck_runs_version'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_agent_runs_job_id_jobs')),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], name=op.f('fk_agent_runs_trigger_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('job_id', 'attempt', name=op.f('uq_agent_runs_job_id'))
    )
    op.create_table('action_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_action_drafts_incident_id_incidents')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_action_drafts_run_id_agent_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_drafts'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_drafts')
    op.drop_table('agent_runs')
    op.drop_index('uq_requests_open', table_name='requests', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_table('requests')
    op.drop_table('jobs')
    op.drop_table('messages')
    op.drop_table('evidence')
    op.drop_table('events')
    op.drop_table('shift_pairs')
    op.drop_table('shift_assignments')
    op.drop_table('sessions')
    op.drop_table('incidents')
    op.drop_table('shifts')
    op.drop_table('equipment')
    op.drop_table('command_receipts')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
