"""Generate the shared session/enums from Python; --check detects drift in CI."""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / "apps/api"))
from app.core.contracts import SessionView, IncidentStatus, ActionStatus, JobStatus


def ts_type(field):
    if "$ref" in field:
        return field["$ref"].rsplit("/", 1)[1]
    if "anyOf" in field:
        return " | ".join(ts_type(part) for part in field["anyOf"])
    if "enum" in field:
        return " | ".join(json.dumps(v) for v in field["enum"])
    if field["type"] == "array":
        return "(" + ts_type(field["items"]) + ")[]"
    return {"string": "string", "integer": "number", "boolean": "boolean", "null": "null",
            "object": "Record<string, unknown>"}[field["type"]]


lines = ["// Generated by scripts/export_contracts.py. Do not edit manually."]
for enum in (IncidentStatus, ActionStatus, JobStatus):
    lines.append(f"export const {enum.__name__}Values = {json.dumps([v.value for v in enum])} as const")
    lines.append(f"export type {enum.__name__} = typeof {enum.__name__}Values[number]")
definitions = {}
for model in (SessionView,):
    schema = model.model_json_schema()
    definitions.update(schema.get("$defs", {}))
    definitions[model.__name__] = schema
for name, schema in definitions.items():
    if "enum" in schema:
        continue
    lines.append(f"export interface {name} {{")
    for key, field in schema["properties"].items():
        optional = "" if key in schema.get("required", []) else "?"
        lines.append(f"  {key}{optional}: {ts_type(field)}")
    lines.append("}")
content = "\n".join(lines) + "\n"
target = root / "apps/web/src/lib/contracts.ts"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != content:
        raise SystemExit("Shared web contracts are stale; run scripts/export_contracts.py")
else:
    target.write_text(content)
