// Generated by scripts/export_contracts.py. Do not edit manually.
export const IncidentStatusValues = ["OPEN", "INVESTIGATING", "ACTION_REQUIRED", "IN_PROGRESS", "PENDING_VERIFICATION", "RESOLVED"] as const
export type IncidentStatus = typeof IncidentStatusValues[number]
export const ActionStatusValues = ["PROPOSED", "APPROVED", "IN_PROGRESS", "COMPLETED", "REJECTED"] as const
export type ActionStatus = typeof ActionStatusValues[number]
export const JobStatusValues = ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "SUPERSEDED"] as const
export type JobStatus = typeof JobStatusValues[number]
export interface SessionView {
  user_id: string
  site_id: string
  role: "worker" | "supervisor"
  display_name: string
  site_name: string
  shift_occurrence_id: string
  duties: (string)[]
}
export interface ActionDetail {
  id: string
  status: ActionStatus
  version: number
  revision: number
  title: string
  scope: string
  completion_criteria: (string)[]
  evidence_refs: (string)[]
  assignee_id: string
  due_at: string
  is_required: boolean
  result_message_id: string | null
  completion_evidence_id: string | null
}
export interface ApprovalDetail {
  id: string
  action_id: string
  action_revision: number
  decision: "APPROVE" | "REJECT"
  reason: string
  payload_hash: string
  approved_payload_snapshot: Record<string, unknown>
  actor_id: string
  created_at: string
}
export interface EvidenceDetail {
  id: string
  source_type: "message" | "log" | "sop" | "case" | "completion_report"
  source_id: string
  source_version: string
  excerpt: string
  content_hash: string
  captured_at: string
}
export interface MessageDetail {
  id: string
  kind: "REPORT" | "NOTE" | "REPLY" | "ACTION_RESULT" | "CORRECTION"
  text: string
  author_id: string
  received_at: string
  reply_to_request_id: string | null
  action_id: string | null
}
export interface RequestDetail {
  id: string
  target_user_id: string
  question: string
  purpose_code: "VERIFY_SCOPE" | "VERIFY_RESULT"
  is_required: boolean
  status: "OPEN" | "ANSWERED"
  response_message_id: string | null
  version: number
}
export interface IncidentDetail {
  id: string
  display_id: string
  equipment_id: string
  status: IncidentStatus
  version: number
  owner_id: string
  review_required: boolean
  review_reason: string | null
  waiting_for_input: boolean
  messages: (MessageDetail)[]
  requests: (RequestDetail)[]
  actions: (ActionDetail)[]
  approvals: (ApprovalDetail)[]
  evidence: (EvidenceDetail)[]
  analysis: Record<string, unknown> | null
  handover: Record<string, unknown> | null
  recent_events: (Record<string, unknown>)[]
  latest_job: Record<string, unknown> | null
  allowed_commands: (string)[]
}
