// Generated by scripts/export_contracts.py. Do not edit manually.
export const IncidentStatusValues = ["OPEN", "INVESTIGATING", "ACTION_REQUIRED", "IN_PROGRESS", "PENDING_VERIFICATION", "RESOLVED"] as const
export type IncidentStatus = typeof IncidentStatusValues[number]
export const ActionStatusValues = ["PROPOSED", "APPROVED", "IN_PROGRESS", "COMPLETED", "REJECTED"] as const
export type ActionStatus = typeof ActionStatusValues[number]
export const JobStatusValues = ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "SUPERSEDED"] as const
export type JobStatus = typeof JobStatusValues[number]
export interface SessionView {
  user_id: string
  site_id: string
  role: "worker" | "supervisor"
  display_name: string
  shift_occurrence_id: string
  duties: (string)[]
}
